tests ~ fix 'esm.sh' transpiled imports
# [why]

Imports via 'http://cdn.esm.sh/...' or 'https://cdn.esm.sh/...' are now broken because of
internal use of 'http' in the transpiled import module. The initial import is being
automatically "upgraded" to 'https' during the import, but the imported module code has
internal secondary 'http' imports (even when imported via an initial 'https'). This causes
the ultimate import error.

```shell
$ deno run --reload "http://cdn.esm.sh/rfc-log-levels@3.17.0"
Download http://cdn.esm.sh/rfc-log-levels@3.17.0
Download https://cdn.esm.sh/rfc-log-levels@3.17.0
error: Modules imported via https are not allowed to import http modules.
  Importing: http://cdn.esm.sh/v90/rfc-log-levels@3.17.0/deno/rfc-log-levels.js
    at https://cdn.esm.sh/rfc-log-levels@3.17.0:3:25

$ curl -#L "http://cdn.esm.sh/rfc-log-levels@3.17.0"
/* esm.sh - rfc-log-levels@3.17.0 */
export * from "http://cdn.esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
export { default } from "http://cdn.esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";

$ curl -#L "https://cdn.esm.sh/rfc-log-levels@3.17.0"
/* esm.sh - rfc-log-levels@3.17.0 */
export * from "http://cdn.esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
export { default } from "http://cdn.esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
```

Using 'https://esm.sh/...' (or http://esm.sh/...) fixes the problem.

```shell
$ deno run --reload "http://esm.sh/rfc-log-levels@3.17.0"
Download http://esm.sh/rfc-log-levels@3.17.0
Download https://esm.sh/rfc-log-levels@3.17.0
Download https://esm.sh/v90/rfc-log-levels@3.17.0/deno/rfc-log-levels.js
Download https://esm.sh/v90/rfc-log-levels@3.17.0/compiled-types/index.d.ts

$ deno run --reload "https://esm.sh/rfc-log-levels@3.17.0"
Download https://esm.sh/rfc-log-levels@3.17.0
Download https://esm.sh/v90/rfc-log-levels@3.17.0/deno/rfc-log-levels.js
Download https://esm.sh/v90/rfc-log-levels@3.17.0/compiled-types/index.d.ts
```

This is because the imported module always uses the "upgraded" https protocol internally.

```shell
$curl -#L "http://esm.sh/rfc-log-levels@3.17.0"
/* esm.sh - rfc-log-levels@3.17.0 */
export * from "https://esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
export { default } from "https://esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";

$ curl -#L "https://esm.sh/rfc-log-levels@3.17.0"
/* esm.sh - rfc-log-levels@3.17.0 */
export * from "https://esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
export { default } from "https://esm.sh/v90/rfc-log-levels@3.17.0/es2015/rfc-log-levels.js";
```