fix/xWait ~ swap `tty.stripAnsi()` with std.fmt.colors replacement
- fixes a run-time error when `tty.stripAnsi()` is used in a `deno compiled` bundle

## notes

```text
error: TypeError: mod8.stripAnsi is not a function
    at Spinner.updateLines (file://$deno$/bundle.js:33138:33)
    at Spinner.set text (file://$deno$/bundle.js:33080:14)
    at new Spinner (file://$deno$/bundle.js:33034:19)
    at wait (file://$deno$/bundle.js:33006:12)
    at file://$deno$/bundle.js:34187:27
```