change ~ refer to current repo for imports (avoids `deno check ...` type errors)
## [why]

Otherwise, type incompatibility errors occur during `deno check`...

```shell
❯ deno check tools\
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/enhance-deno-CMD-shims.deno.ts
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/enhance-npm-CMD-shims.deno.ts
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/lib/$deps.ts
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/lib/$shared.ts
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/lib/funk.ts
Check file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tools/resolve-from-imap.deno.ts
TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: RID, NotFound, PermissionDenied, ConnectionRefused, ConnectionReset, ConnectionAborted, NotConnected, AddrInUse, AddrNotAvailable, BrokenPipe, AlreadyExists, InvalidData, TimedOut, Interrupted, WouldBlock, WriteZero, UnexpectedEof, BadResource, Http, Busy, NotSupported, FilesystemLoop, IsADirectory, NetworkUnreachable, NotADirectory, pid, ppid, noColor, PermissionOptions, test, env, Start, Current, End, FsFile, File, stdin, stdout, stderr, Buffer, FsEventFlag, ProcessStatus, Process, Signal, Command, ChildProcess, PermissionName, PermissionState, PermissionDescriptor, PermissionStatus, Permissions, permissions, build, version, args, customInspect, mainModule, RecordType, ServeHandler, ServeUnixHandler, Server, Addr, TlsListener, TcpListener, UnixListener, TlsCertifiedKeyOptions
declare namespace DenoV1NS {
~~~~~~~
    at file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/vendor/@types/deno@1.46.3/lib.deno.ns.d.ts:7:1

    Conflicts are in this file.
    declare namespace DenoV1NS {
    ~~~~~~~
        at https://cdn.jsdelivr.net/gh/rivy/deno.dxx@7a17530aab/vendor/@types/deno@1.46.3/lib.deno.ns.d.ts:7:1

TS2374 [ERROR]: Duplicate index signature for type 'number'.
    [rid: number]: unknown;
    ~~~~~~~~~~~~~~~~~~~~~~~
    at file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/vendor/@types/deno@1.46.3/lib.deno.ns.d.ts:4117:5

Found 2 errors.

error: Type checking failed.
```