maint/dev ~ (tasks) suppress info/complaint when test AssertionError occurs
- suppress the distracting `info` message upon a test failure due to an `AssertionError`

## notes

Example `AssertionError` and related "info/hint" message...

```text
 ERRORS

00.project.style.test.ts:290 :: style ~ `cspell lint --no-progress --config ./.vscode/cspell.json **` => ./tests/$shared.ts:210:8
error: Error:
# ---- test log:begin > ----
`cspell` status { success: false, code: 1 }
c:\Users\Roy\AARK\Projects\deno\dxx\repo.GH\src\lib\$shared.ts:440:12 - Unknown word (MSDV)
c:\Users\Roy\AARK\Projects\deno\dxx\repo.GH\src\lib\$shared.ts:441:11 - Unknown word (MSDV)
CSpell: Files checked: 76, Issues found: 2 in 1 files
# ---- test log:end . ------
AssertionError: `cspell` check succeeds
    at assert (https://deno.land/std@0.134.0/testing/asserts.ts:222:11)
    at file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tests/00.project.style.test.ts:303:4
    at async fn (file:///C:/Users/Roy/AARK/Projects/deno/dxx/repo.GH/tests/$shared.ts:224:6)
    at async innerWrapped (ext:cli/40_test.js:300:5)
    at async exitSanitizer (ext:cli/40_test.js:201:27)
    at async outerWrapped (ext:cli/40_test.js:239:22)

    info: This program assigned to Object.prototype.__proto__, which Deno disables by default.
    hint: If this caused the error, run again with --unsafe-proto to restore it.

 FAILURES

00.project.style.test.ts:290 :: style ~ `cspell lint --no-progress --config ./.vscode/cspell.json **` => ./tests/$shared.ts:210:8

FAILED | 58 passed | 1 failed | 1 ignored (13s)

error: Test failed
```

This just distracts from the actual error.

The likely cause is using an early version of the assert functions from Deno std@0.134.0
("assert (https://deno.land/std@0.134.0/testing/asserts.ts:222:11)"). A true fix would
either be moving to a more modern version of assert (which could cause other failures for
earlier Deno versions) or just using a locally rewritten set of assert functions which
don't have the issue.